apiVersion: v1
baseDomain: stretched.lcl
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 5
metadata:
  name: openshift
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDX2vDUeL2p9twbVcH+64Iawx5viFhh+P0dWoa/5B4hc christian@ubuntu-servers'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFaTCCA1GgAwIBAgIRALLJWxr/p0GVShTLOn1ZJT0wDQYJKoZIhvcNAQELBQAw
  TTELMAkGA1UEBhMCQVQxDzANBgNVBAgTBlN0eXJpYTESMBAGA1UEBxMJR2xlaXNk
  b3JmMRkwFwYDVQQDExBjYS5zdHJldGNoZWQubGNsMCAXDTI2MDMxMTA0NTc1MloY
  DzIxMjYwMzEyMDQ1NzUyWjBNMQswCQYDVQQGEwJBVDEPMA0GA1UECBMGU3R5cmlh
  MRIwEAYDVQQHEwlHbGVpc2RvcmYxGTAXBgNVBAMTEGNhLnN0cmV0Y2hlZC5sY2ww
  ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC/rPwYiH9Rk2MFYlIwyb/h
  cs2qXipT3zEC7tnW9HDJ5RqvST71PV24lYEzgMx5BeZ2HpXPDoOk4ghTSaHbhYBE
  PQ0c0dgkCfLqTySMkhsD+xcbHixtIFWpKi92MazchjVbZYykwR/oHYpJHYjE7qeK
  YAE07DxMwYeQhA/UUSbanmkgyUm52F3HdSJQcU2gzzHjU19YH/ljM4X+MX1MyBng
  0oVE913EvTYH6MtmL27KDwQSiqYpTucGBkxaOHnR+Wnj2Ac7jqACyelKRwKFNOh9
  Lg8Gg0h4j51wjwDGSPyWE26hzAKIY3rb5Vzp458ZMBRnu7I5AedzTGcHLl2GGvUK
  HAlBgc//D1hr+Nq9xQzBcq3s0wWCslPmyPDIFDq6GggsD+dwBXR3L8MRQFMAs2Q2
  Ywd3/T6AEPyoTOAygJRT3N9/T+675fa1Z9eTGBU00LF0c20qwVW/D7Njt5Y0AyvO
  wt+kDDRIYYCu8T44xlOLRDT5cVSH5oCrlR3T7XhG5N5cAx172WGrkVc9y/bP2y8M
  a/UvPnIxrSBacN6+bh0mfsOECTx70dxwImd8765LbtZHJWpuyNAclNIx3NQ+Iecx
  52ByatDgZaMmFYMp1zkl8/OcfvLs0c1DT3a52/B7a6xG/8SULUNoBN74BnaYN2rK
  hwzTT9vhd57s4fKsClljcwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0T
  AQH/BAUwAwEB/zAdBgNVHQ4EFgQUbjPHheAv6SlpM6ngPQ3Y/tAzCVkwDQYJKoZI
  hvcNAQELBQADggIBAHHTRipsQdMHOPPcS97WpJGRPm0ZNmSZG8JQJFjiYriD5nhQ
  NbONJ2K5y8y+1rfjsrWt8WUZ+b+qkYQCR3jPmUgv/PaG69oEAARsyUCYB1WASBmh
  KRdlutLFh8PYdL8OxTZnU8HzFeFoBSH2jN2Uyh68Y/us/XcpP3IKWrM6Jbwf0Kxa
  cJ+jL+fHNDQU2ypmrxa5G9UrPkuPvQrd1hAZmeV4sHQtW/Mk69vdopB3fTS0QtLZ
  G3UpIEuQT5+MO627g5SCKGsUuHo0E5kewfk2adLz2FydMZFZNuT+Kr/4jsrwQI9+
  blGqUCktS0p2zgEYHxAcwWJAuDwFeBV2io5U7mEMzCxmoMyr52tvZhGepNlX8mVa
  v3fcAsNHwfuC6epIME7lqLHdneOf1w6Oz71iXrd/nfzJDKhdoxz2FIs6/Ejf2Guq
  4y57cMHktxEmWT6dSInZ4/jJooGoMowK/VhGNWh8fsnShDT2eaPLPfr6NizVbnBB
  doxQhSpV+P/oRhikFMp5ixAiZx0zGwcx358LHDqE3zd3kAKT2s1Z4wDZgaV3iaCA
  T4a/hUt7W7AEQz1gZniVaxlRnsOvJZ2RvVZWV7N1HzY1zOjwMDamG2m8FhGLcsAN
  8vx/MFrL9KfmCPXBD0IgWNAKbkfXjZN2dnxMevLYGiu/lb503IRR/BNUsDal
  -----END CERTIFICATE-----
